kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  type: NodePort                     # 이거
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30239                # 이거
  selector:
    k8s-app: kubernetes-dashboard
