apiVersion: v1
kind: Service
metadata:
  name: my-front
  labels:
    run: my-front
spec:
  type: NodePort     # 서비스 타입
  ports:
  - nodePort: 30000  # 외부 포트
    port: 8080       # 서비스 포트
    targetPort: 3000   # 컨테이너 포트(pod 포트)
    protocol: TCP
    name: http
  selector:
    app: front

